---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
        - name: flask-backend
          image: 261331872489.dkr.ecr.ap-southeast-1.amazonaws.com/flask-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PLATE_DETECTION_URL
              value: "http://plate-detection-service.default.svc.cluster.local/"
