---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/contents"
spec:
  type: ClusterIP
  selector:
     app: flask-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
