---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plate-detection
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: plate-detection
  template:
    metadata:
      labels:
        app: plate-detection
    spec:
      containers:
        - name: plate-detection
          image: 261331872489.dkr.ecr.ap-southeast-1.amazonaws.com/plate-detection:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
