apiVersion: v1
kind: Secret
metadata:
  name: ec2-pass-secret
type: Opaque
data:
  ACCOUNT_ID: QUtJQTJYQUlSV1pLTVhaNVNYUEg=
  ACCESS_KEY: NjBQMEtFMTNpdDdTZEdUWGIrL1VSTXhaMTdmZU9SKzk3UGU0blFVRg==
  BUCKET_NAME: a2RnZWMyczM=
